[dev] show battery reminder by easy to see GUI
sugikazu75/riberry pull request #2
Opened 2024-10-09 09:35 UTC by HarukiKozukapenguin

I develop new [GUI](https://drive.google.com/file/d/1vjq5bNMCUjl4o5YUgqSbA79bBDmIaRcb/view?resourcekey) (thanks by @KenMat765) to show battery reminder for JSK aerial robotics team.

2024-10-09 12:41 UTC, sugikazu75 commented
@HarukiKozukapenguin 
Are files under `lib/M5AtomS3` public code? If so, please do not include git commit and get automatically when build like as `add_custom_command` in cmake (FYI: https://docs.platformio.org/en/latest/scripting/custom_targets.html).

2024-10-09 13:06 UTC, sugikazu75 requested changes

2024-10-09 13:06 UTC, sugikazu75 commented on firmware/atom_s3_rosserial_message_display/src/main.cpp
> +    M5.Lcd.fillScreen(M5.Lcd.color565(255, 0, 0));
indent

2024-10-09 13:06 UTC, sugikazu75 commented on firmware/atom_s3_rosserial_message_display/src/main.cpp
> +int batcell = 4;
Please do not use magic number which is specific value for each robots.

2024-10-09 13:06 UTC, sugikazu75 commented on firmware/atom_s3_rosserial_message_display/src/main.cpp
> +
these lines should be implemented other file

2024-10-09 13:10 UTC, sugikazu75 commented
> @HarukiKozukapenguin Are files under `lib/M5AtomS3` public code? If so, please do not include git commit and get automatically when build like as `add_custom_command` in cmake (FYI: https://docs.platformio.org/en/latest/scripting/custom_targets.html).

I will add example to generate `ros_lib` automatically.

2024-10-10 09:12 UTC, sugikazu75 commented
@HarukiKozukapenguin  
This is an example to generate ros_lib automatically.  https://github.com/sugikazu75/riberry/pull/3

2024-10-10 14:02 UTC, HarukiKozukapenguin commented
@sugikazu75 
I can get system that change battery cell by [this commit](https://github.com/sugikazu75/riberry/pull/2/commits/ad650176a431cbd563db1ca5d15530c84e5bc4b7)
(e.g. rosrun rosserial_python serial_node.py _port:=/dev/ttyACM0 __ns:=robot_ns **_bat_cell:=4**)

I also separate battery display class by making lib in lib directory ([this commit](https://github.com/sugikazu75/riberry/pull/2/commits/807e914d183677d37d345a7b17cb731a17dbb7a6))

2024-10-10 14:41 UTC, HarukiKozukapenguin commented on firmware/atom_s3_rosserial_message_display/src/main.cpp
> +int batcell = 4;
@sugikazu75
I can get system that change battery cell by [this commit](https://github.com/sugikazu75/riberry/pull/2/commits/ad650176a431cbd563db1ca5d15530c84e5bc4b7)
(e.g. rosrun rosserial_python serial_node.py _port:=/dev/ttyACM0 __ns:=robot_ns _bat_cell:=4)

2024-10-10 14:41 UTC, HarukiKozukapenguin commented on firmware/atom_s3_rosserial_message_display/src/main.cpp
> +
I also separate battery display class by making lib in lib directory ([this commit](https://github.com/sugikazu75/riberry/pull/2/commits/807e914d183677d37d345a7b17cb731a17dbb7a6))

2024-10-10 14:43 UTC, HarukiKozukapenguin commented
> @HarukiKozukapenguin Are files under `lib/M5AtomS3` public code? If so, please do not include in git commit and get automatically when build like as `add_custom_command` in cmake (FYI: https://docs.platformio.org/en/latest/scripting/custom_targets.html).

I include m5stack/M5AtomsS3 file and add the file  in the command of _pio run -t upload_

2024-10-14 09:04 UTC, sugikazu75 commented
@HarukiKozukapenguin 
This PR is ready to merge. Please test it with real machine (not necessary to flying test. just check LCD and real topic value).
`roslaunch robot_ns bringup.launch`
`rosrun rosserial_python serial_node.py _port:=tty**** __ns:=robot_ns`

2024-10-14 10:48 UTC, HarukiKozukapenguin commented
@sugikazu75 
I tested with real machine, and it works` well. ([video](https://drive.google.com/file/d/1mCmK_9BThxoiokR91uYOh2mzOXKSEUvq/view?usp=sharing))

2024-10-15 08:12 UTC, sugikazu75 approved these changes

2024-10-15 08:13 UTC, merged